name: Python app

on:
  pull_request:
    branches: [ "main" ]
    types: ["closed"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout: 5
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      working-directory: app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run app
      working-directory: app
      run: python3 devops.py

