name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
    types: ["closed"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v3
    - name: Build & Run Docker image
      run: docker-compose up --build -d
