name: Python app

on:
  pull_request:
    branches: [ "main" ]
    types: ["closed"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Run app2
      working-directory: app2
      run: python3 main.py

